version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/cli"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/convert"
    schedule:
      interval: "weekly"
