[workspace]
members = [".", "runtime"]
exclude = ["convert"]

[workspace.package]
version = "0.11.0"
keywords = ["bitcoin", "wallet", "descriptor-wallet", "psbt", "taproot"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://lnp-bp.org"
repository = "https://github.com/BP-WG/bp-wallet"
rust-version = "1.60" # Due to rust-amplify
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.0.1"
strict_encoding = "2.5.0"
bp-std = "0.11.0"
bp-esplora = "0.11.0"
serde_crate = { package = "serde", version = "1", features = ["derive"] }
serde_with = "3.1.0"
toml = "0.7.6"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }

[package]
name = "bp-wallet"
version = { workspace = true }
description = "Modern, minimalistic & standard-compliant cold wallet library"
keywords = { workspace = true }
categories = { workspace = true }
readme = "README.md"
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "bp"
path = "src/bin/bp/main.rs"

[lib]
name = "bpw"

[dependencies]
amplify = { workspace = true, features = ["serde"] }
strict_encoding = { workspace = true }
bp-runtime = { path = "runtime", features = ["serde"] }
bp-std = { workspace = true, features = ["serde"] }
bp-esplora = { workspace = true }
log = { workspace = true }
env_logger = "0.10.0"
clap = { version = "4.1.8", features = ["derive", "env"] }
shellexpand = "3.0.0"
serde_crate = { workspace = true }
serde_yaml = "0.9.19"
toml = "0.7.6"

[features]
default = []
all = []

[patch.crates-io]
bp-primitives = { git = "https://github.com/BP-WG/bp-core", branch = "primitives" }
bp-std = { git = "https://github.com/BP-WG/bp-std" }
bp-esplora = { git = "https://github.com/BP-WG/bp-esplora-client" }
